In [1]:
import pandas as pd

In [17]:
from google.colab import files

In [18]:
uploaded = files.upload()

Saving placement_missing.csv to placement_missing (1).csv

In [19]:
df=pd.read_csv('placement_missing.csv')

In [20]:
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96   NaN          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          90 non-null     float64
 1   resume_score  90 non-null     float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [22]:
df1=df.dropna()

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          80 non-null     float64
 1   resume_score  80 non-null     float64
 2   placed        80 non-null     int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [24]:
df.fillna(0,inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [25]:
uploaded = files.upload()

Saving placement_missing.csv to placement_missing (2).csv

In [26]:
df=pd.read_csv('placement_missing.csv')

In [27]:
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96   NaN          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          90 non-null     float64
 1   resume_score  90 non-null     float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [31]:
df2 = df.copy()
df2['placed'].fillna(130, inplace=True)

/tmp/ipykernel_1387/4134835639.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['placed'].fillna(130, inplace=True)

In [36]:
df2 = df.copy()
df2['cgpa'] = df2['cgpa'].fillna(130)

In [37]:
x=df2['cgpa'].mean()

In [41]:
df2['cgpa'].fillna(x,inplace=True)

/tmp/ipykernel_1387/211359833.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['cgpa'].fillna(x,inplace=True)

In [42]:
x

np.float64(19.214000000000002)

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  90 non-null     float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [46]:
x1=df2['resume_score'].mean()

In [47]:
df2['resume_score'].fillna(x,inplace=True)

/tmp/ipykernel_1387/217608652.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['resume_score'].fillna(x,inplace=True)

In [48]:
x1

np.float64(6.934333333333332)

In [49]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

now label encoding

In [ ]:
# #from sklearn.preprocessing import LabelEncoder
# #df[col_name].value_counts()
# obj=LabelEncoder()
# encoded_values=obj.fit_transform(df.diagoniso)  #encode ho k is me ayga
# df[encoded_values]=encoded_vlaues
# df.loc[ : ,'encoded_values','diagnoses']

In [51]:
#import from files
df1=pd.read_csv("/content/card_transdata.csv")

In [52]:
df1

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
13742,3.595141,0.781622,0.819360,1.0,1.0,0.0,0.0,0.0
13743,13.262700,0.120003,1.726913,1.0,0.0,1.0,0.0,0.0
13744,27.420012,3.263238,0.987227,1.0,0.0,0.0,0.0,0.0
13745,7.043451,0.072637,0.297440,1.0,0.0,0.0,1.0,0.0
13746,55.072000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df['fraud'].value_counts()

fraud
0.0    12580
1.0     1166
Name: count, dtype: int64

In [54]:
legit = df[df['fraud'] == 0]
fraud = df[df['fraud'] == 1]

In [55]:
legit.shape

(12580, 8)

In [56]:
fraud.shape

(1166, 8)

df.sample(n) is used to randomly extract a specified number of rows from a DataFrame, primarily used in data science for under-sampling majority classes to balance imbalanced datasets.

In [57]:
legit_sample=legit.sample(n=30)

In [60]:
legit_sample.shape

(30, 8)

In [62]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [63]:
# 1. Features (X) aur Target (y) ko alag karein
X = new_dataset.drop(columns='fraud', axis=1)
y = new_dataset['fraud']

# 2. Data ko Training aur Testing mein split karein
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape)

(956, 7) (240, 7)