In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving placement (1).csv to placement (1).csv

In [ ]:

df = pd.read_csv('placement (1).csv')

In [ ]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.head()  #pehle 5 records

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.head(10) #1st 10 records

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1
5  8.77          6.19       1
6  5.34          7.09       0
7  6.56          6.29       0
8  6.32          6.71       0
9  7.69          7.12       1

In [ ]:
df.tail() #last 5 record

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [ ]:
df.tail(50)

    cgpa  resume_score  placed
50  8.22          6.74       1
51  6.54          7.39       0
52  5.90          7.50       0
53  6.00          7.16       0
54  5.92          7.18       0
55  6.94          6.87       1
56  6.13          6.43       0
57  6.34          7.21       0
58  6.47          7.37       0
59  5.95          7.57       0
60  5.87          6.64       0
61  6.89          7.96       1
62  5.75          8.43       0
63  8.65          7.58       1
64  7.93          8.09       1
65  6.04          8.75       0
66  8.35          8.02       1
67  6.59          6.81       1
68  6.01          7.49       0
69  8.06          9.06       1
70  7.12          7.41       1
71  7.34          8.22       1
72  7.63          7.98       1
73  5.76          6.48       0
74  5.54          7.36       0
75  6.34          7.94       1
76  9.40          5.50       1
77  5.88          6.92       0
78  5.79          5.66       0
79  5.27          7.28       0
80  7.83          7.70       1
81  6.12          6.72       0
82  7.92          6.06       1
83  7.60          8.08       1
84  5.76          6.49       0
85  6.72          5.46       0
86  6.18          5.76       0
87  5.62          5.05       0
88  8.07          6.07       1
89  5.99          7.49       0
90  5.85          5.56       0
91  8.28          6.30       1
92  5.43          6.18       0
93  9.31          7.39       1
94  8.01          4.95       1
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.shape

(100, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [ ]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
df['cgpa'].value_counts()

cgpa
8.14    2
6.09    2
8.22    2
6.18    2
6.34    2
       ..
9.31    1
8.01    1
6.33    1
8.23    1
6.65    1
Name: count, Length: 89, dtype: int64

In [ ]:
df.groupby('cgpa').mean()

      resume_score  placed
cgpa
5.27          7.28     0.0
5.34          7.09     0.0
5.43          6.18     0.0
5.44          6.54     0.0
5.46          6.73     0.0
...            ...     ...
8.87          7.19     1.0
8.88          5.93     1.0
9.05          8.21     1.0
9.31          7.39     1.0
9.40          5.50     1.0

[89 rows x 2 columns]

Statistics

In [ ]:
df.count()

cgpa            100
resume_score    100
placed          100
dtype: int64

In [ ]:
df.mean()

cgpa            6.9422
resume_score    6.9305
placed          0.5000
dtype: float64

In [ ]:
df.std()

cgpa            1.119200
resume_score    0.979608
placed          0.502519
dtype: float64

In [ ]:
df.min()

cgpa            5.27
resume_score    4.95
placed          0.00
dtype: float64

In [ ]:
df.max()

cgpa            9.40
resume_score    9.06
placed          1.00
dtype: float64

In [ ]:
df.describe()

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [ ]:
#df.drop(index, axis=0)  for removing specific row.through specific index.,,not permanant

To drop rows permanently, you can use `inplace=True` or reassign the DataFrame.

In [ ]:
# Example: Dropping a row by its index permanently using inplace=True
# Let's say you want to drop the row with index 0
# df.drop(index=0, inplace=True)
# display(df.head())

# Or, by reassigning the DataFrame (which is generally preferred for clarity)
# df = df.drop(index=0)
# display(df.head())

# To demonstrate, let's drop rows where 'cgpa' is less than 5 (just an example)
# Make sure to run this only if you want to modify your df permanently
# df_original_shape = df.shape[0]
# df = df[df['cgpa'] >= 5]
# print(f"Number of rows dropped: {df_original_shape - df.shape[0]}")
# display(df.head())

Selection in Pandas--> by iloc & loc or we can use python native approach

In [ ]:
#iloc--> index based

#creating dataset
df=pd.DataFrame({
    "Name":['Ali','Hamza','Nimrah'],
    "CGPA":[3.91,3.95,3.80],
    "Age":[20,19,20]

})

In [ ]:
print(df)

     Name  CGPA  Age
0     Ali  3.91   20
1   Hamza  3.95   19
2  Nimrah  3.80   20

In [ ]:
df.iloc[0,0]

'Ali'

In [ ]:
df.iloc[2,1]

np.float64(3.8)

In [ ]:
#y range access
df.iloc[0,0:3]

Name     Ali
CGPA    3.91
Age       20
Name: 0, dtype: object

In [ ]:
df.iloc[0:2,0:3]

    Name  CGPA  Age
0    Ali  3.91   20
1  Hamza  3.95   19

In [ ]:
df.iloc[0:,0:3]

     Name  CGPA  Age
0     Ali  3.91   20
1   Hamza  3.95   19
2  Nimrah  3.80   20

In [ ]:
df.iloc[:,:]

     Name  CGPA  Age
0     Ali  3.91   20
1   Hamza  3.95   19
2  Nimrah  3.80   20

In [ ]:
df.iloc[2]

Name    Nimrah
CGPA       3.8
Age         20
Name: 2, dtype: object

In [ ]:
df.iloc[:,0:2]

     Name  CGPA
0     Ali  3.91
1   Hamza  3.95
2  Nimrah  3.80

In [ ]:
#by nested list
df.iloc[:,[0,2]]

     Name  Age
0     Ali   20
1   Hamza   19
2  Nimrah   20

In [ ]:
#loc me label based
df.loc[0:3,'Name'] #data idexing ki based pr hai agr label me krna tw convert

0       Ali
1     Hamza
2    Nimrah
Name: Name, dtype: object

In [ ]:
labels=['a','b','c']
df=pd.DataFrame({
    "Name":['Ali','Hamza','Nimrah'],
    "CGPA":[3.91,3.95,3.80],
    "Age":[20,19,20],


},index=labels)

In [ ]:
df

     Name  CGPA  Age
a     Ali  3.91   20
b   Hamza  3.95   19
c  Nimrah  3.80   20

In [ ]:
df.loc['a','CGPA']

np.float64(3.91)

In [ ]:
df.loc[['a','b'],'CGPA']

a    3.91
b    3.95
Name: CGPA, dtype: float64

In [ ]:
df.loc[0 : 3,'CGPA']  #work on labels

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [ ]:
#in iloc-->last index exclusive & in loc its inclusive

correlation
positive correlation---> directly proproltional 1to 0
negative co--> inverese proportion -1 to 0
no correlation --> 0